<?php

namespace App\Utils\Constants;

class FixedValuesConstants
{
    const STATUS_GAME_OF_NINE = 'STATUS_GAME_OF_NINE';
    const STATUS_GAME_OF_THIRTEEN = 'STATUS_GAME_OF_THIRTEEN'; 
    const STATUS_GAME_OF_ELEVEN = 'STATUS_GAME_OF_ELEVEN';
    const STATUS_GAME_OF_FIFTEEN = 'STATUS_GAME_OF_FIFTEEN';
    const STATUS_GAME_OF_EIGHTEEN = 'STATUS_GAME_OF_EIGHTEEN';
    const STATUS_GAME_OF_FOURTEEN = 'STATUS_GAME_OF_FOURTEEN';
    const STATUS_GAME_OF_TWENTY_ONE = 'STATUS_GAME_OF_TWENTY_ONE';
    const STATUS_GAME_OF_TWENTY_TREE = 'STATUS_GAME_OF_TWENTY_TREE';
    const STATUS_GAME_VALIDATED = 'STATUS_GAME_VALIDATED';
    const STATUS_GAME_INCOMPLETE = 'STATUS_GAME_INCOMPLETE';
    const STATUS_BET_WIN =  'STATUS_BET_WIN';
    const STATUS_BET_LOST   = 'STATUS_BET_LOST';

    const TYPE_TRANSACTION_DEPOSIT = 'TYPE_TRANSACTION_DEPOSIT';
    const TYPE_TRANSACTION_WITHDRAW = 'TYPE_TRANSACTION_WITHDRAW';
    const TYPE_BET_NAP1_POTO =  'TYPE_BET_NAP1_POTO';
    const TYPE_BET_NAP1_BLOQUE = 'TYPE_BET_NAP1_BLOQUE';
    const TYPE_BET_NAP2 = 'TYPE_BET_NAP2';
    const TYPE_BET_NAP3 = 'TYPE_BET_NAP3';
    const TYPE_BET_NAP4 = 'TYPE_BET_NAP4';
    const TYPE_BET_NAP5 = 'TYPE_BET_NAP5';
    const TYPE_BET_TCHIGAN = 'TYPE_BET_TCHIGAN';
    const TYPE_BET_PERM2 = 'TYPE_BET_PERM2';
    const  TYPE_BET_PERM3 = 'TYPE_BET_PERM3';
    const TYPE_PERIOD_DAY = 'TYPE_PERIOD_DAY';
    const TYPE_PERIOD_WEEK = 'TYPE_PERIOD_WEEK';
    const TYPE_PERIOD_MONTH = 'TYPE_PERIOD_MONTH';
    const TYPE_PERIOD_YEAR = 'TYPE_PERIOD_YEAR';

    const TYPE_CATEGORIE_DYNAMIQUE = 'TYPE_CATEGORIE_DYNAMIQUE';
    const TYPE_CATEGORIE_MOYENNE = 'TYPE_CATEGORIE_MOYENNE';
    const TYPE_CATEGORIE_FAIBLE = 'TYPE_CATEGORIE_FAIBLE';
    const TYPE_WALLET_MAIN = 'TYPE_WALLET_MAIN';
    const TYPE_WALLET_REATTACH = 'TYPE_WALLET_REATTACH';

}
